package.path = "src/?.lua;" .. package.path
local A = dofile("tests/assert.lua")
local protocol = require("protocol")

A.eq(protocol.validate(nil), nil, "nil")
A.eq(protocol.validate({ type = "nope" }), nil, "unknown")
A.eq(protocol.validate({ type = "stick", x = 1 }), nil, "short stick")

local stick = protocol.validate({ type = "stick", x = 1, y = 0, z = -1 })
A.eq(stick.x, 1, "stick x")
A.eq(protocol.validate({ type = "set_mode", mode = "auto" }).mode, "auto", "mode")
A.eq(protocol.validate({ type = "set_mode", mode = "hover" }), nil, "bad mode")
A.eq(protocol.validate({ type = "set_waypoint", x = 3, z = 4 }).z, 4, "waypoint")
A.eq(protocol.validate({ type = "set_profile", profile = "cruise" }).profile, "cruise", "profile")
A.eq(protocol.validate({ type = "return_to_user", x = 8, z = 9 }).x, 8, "return")
A.eq(protocol.validate({ type = "emergency" }).type, "emergency", "estop")
A.eq(protocol.validate({ type = "clear_emergency" }).type, "clear_emergency", "clear")
A.eq(protocol.validate({ type = "diagnostic_enter", hover = true }).hover, true, "diag enter")
A.eq(protocol.validate({ type = "diagnostic_set", device = "rsc10", rpm = 40 }).rpm, 40, "diag rpm")
A.eq(protocol.validate({ type = "diagnostic_set", device = "relay7", side = "bottom", level = 15 }).side, "bottom", "diag relay")
A.eq(protocol.validate({ type = "diagnostic_set", device = "relay7" }), nil, "diag relay missing side")
A.eq(protocol.validate({ type = "diagnostic_elevation", rpm = 80 }).rpm, 80, "elevation")
local queued = protocol.validate({ type = "set_altitude", y = 400 })
A.eq(protocol.keep(queued, { type = "status", altitude = 1 }), queued, "a non-command does not drop altitude")
A.eq(protocol.keep(queued, { type = "set_altitude", y = 250 }).y, 250, "a new altitude replaces the queued one")
local stuck = protocol.keep(queued, { type = "stick", x = 1, y = 0, z = 0 })
A.eq(stuck.type, "stick", "a stick after an altitude still flies")
A.eq(stuck.x, 1, "the stick axis is kept")
A.eq(stuck.latched_altitude, 400, "a stick does not drop the queued altitude")
local released = protocol.keep(stuck, { type = "stick", x = 0, y = 0, z = 0 })
A.eq(released.type, "stick", "a later stick still flies")
A.eq(released.latched_altitude, 400, "a stick repeat or release keeps the altitude")
local bearing = protocol.keep(queued, { type = "set_bearing", bearing = 1 })
A.eq(bearing.type, "set_bearing", "bearing still replaces a queued altitude")
A.eq(bearing.latched_altitude, nil, "bearing entry is not an altitude")
